repos:
  # generic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [backend] # set the project directory
      - id: ruff-format
        args: [backend] # set the project directory
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check
        language: python
        types_or: [python, pyi, jupyter]
        additional_dependencies: [ty]
        args: [--project=backend, --python=backend/.venv]

  # svelte
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.10
    hooks:
      - id: biome-check
        args: [backend] # set the project directory
  - repo: local
    hooks:
      - id: svelte-check
        name: svelte-check
        entry: svelte-check --workspace frontend
        language: node
        types_or: [javascript, ts, svelte, json]
        additional_dependencies: [svelte-check]
