name: minipost

services:
  minipost:
    container_name: minipost
    build: .
    # no image to pull yet
    ports:
      - 8000:8000
    volumes:
      # FIXME: using these direct file paths makes some weird stuff happen
      - ./config.toml:/app/backend/config.toml:ro
      - ./minipost.db:/app/backend/minipost.db
    restart: unless-stopped
