name: minipost

services:
  minipost:
    container_name: minipost
    image: ghcr.io/hackysphere/minipost
    # build: .
    ports:
      - 8000:8000
    volumes:
      - ./minipost:/app/backend/data
    restart: unless-stopped
