USERNAME_MIN_CHARS = 4
USERNAME_MAX_CHARS = 24
POST_MAX_CHARS = 300
USER_MAX_POSTS = 15

# all in seconds
# use -1 for RATE_LIMIT to disable
RATE_LIMIT = 500  # requests per time window
RATE_LIMIT_WINDOW = 60  # time window for requests

BEHIND_PROXY = false
