// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * NewPostBodyOLD
 */
export type NewPostBodyOld = {
	/**
	 * Content
	 */
	content: string;
	/**
	 * User Id
	 */
	user_id: string;
};

/**
 * Post
 */
export type Post = {
	/**
	 * Uuid
	 */
	uuid: string;
	/**
	 * Posted On
	 */
	posted_on: number;
	/**
	 * Content
	 */
	content: string;
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * Replies
	 */
	replies: Array<PostBase> | null;
};

/**
 * PostBase
 */
export type PostBase = {
	/**
	 * Uuid
	 */
	uuid: string;
	/**
	 * Posted On
	 */
	posted_on: number;
	/**
	 * Content
	 */
	content: string;
	/**
	 * User Id
	 */
	user_id: string;
};

/**
 * ReplyReturn
 */
export type ReplyReturn = {
	reply: PostBase;
	/**
	 * Parent Id
	 */
	parent_id: string;
};

/**
 * User
 */
export type User = {
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * Creation Ts
	 */
	creation_ts: number;
	/**
	 * Username
	 */
	username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type GetLatestPostsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Count
		 */
		count?: number;
	};
	url: "/api/posts";
};

export type GetLatestPostsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetLatestPostsError =
	GetLatestPostsErrors[keyof GetLatestPostsErrors];

export type GetLatestPostsResponses = {
	/**
	 * Response Get Latest Posts
	 *
	 * Successful Response
	 */
	200: Array<Post>;
};

export type GetLatestPostsResponse =
	GetLatestPostsResponses[keyof GetLatestPostsResponses];

export type CreatePostData = {
	body: NewPostBodyOld;
	path?: never;
	query?: never;
	url: "/api/posts";
};

export type CreatePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
	/**
	 * Successful Response
	 */
	201: Post;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetPostsByUseridData = {
	body?: never;
	path: {
		/**
		 * User Id
		 */
		user_id: string;
	};
	query?: never;
	url: "/api/users/{user_id}/posts";
};

export type GetPostsByUseridErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPostsByUseridError =
	GetPostsByUseridErrors[keyof GetPostsByUseridErrors];

export type GetPostsByUseridResponses = {
	/**
	 * Response Get Posts By Userid
	 *
	 * Successful Response
	 */
	200: Array<Post>;
};

export type GetPostsByUseridResponse =
	GetPostsByUseridResponses[keyof GetPostsByUseridResponses];

export type DeletePostData = {
	body?: never;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}";
};

export type DeletePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetPostData = {
	body?: never;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}";
};

export type GetPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
	/**
	 * Successful Response
	 */
	200: Post;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type CreateReplyData = {
	body: NewPostBodyOld;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}/reply";
};

export type CreateReplyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateReplyError = CreateReplyErrors[keyof CreateReplyErrors];

export type CreateReplyResponses = {
	/**
	 * Successful Response
	 */
	201: ReplyReturn;
};

export type CreateReplyResponse =
	CreateReplyResponses[keyof CreateReplyResponses];

export type DeleteReplyData = {
	body?: never;
	path: {
		/**
		 * Reply Uuid
		 */
		reply_uuid: string;
	};
	query?: never;
	url: "/api/replies/{reply_uuid}";
};

export type DeleteReplyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteReplyError = DeleteReplyErrors[keyof DeleteReplyErrors];

export type DeleteReplyResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetUserData = {
	body?: never;
	path: {
		/**
		 * User Id
		 */
		user_id: string;
	};
	query?: never;
	url: "/api/users/{user_id}";
};

export type GetUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
	/**
	 * Successful Response
	 */
	200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
