// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * Body_create_account
 */
export type BodyCreateAccount = {
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * Body_create_post
 */
export type BodyCreatePost = {
	/**
	 * Body
	 */
	body: string;
};

/**
 * Body_create_reply
 */
export type BodyCreateReply = {
	/**
	 * Body
	 */
	body: string;
};

/**
 * Body_delete_account
 */
export type BodyDeleteAccount = {
	/**
	 * Password
	 */
	password: string;
};

/**
 * Body_login
 */
export type BodyLogin = {
	/**
	 * Grant Type
	 */
	grant_type: string;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * Body_set_password
 */
export type BodySetPassword = {
	/**
	 * Old Password
	 */
	old_password: string;
	/**
	 * New Password
	 */
	new_password: string;
};

/**
 * Body_set_username
 */
export type BodySetUsername = {
	/**
	 * New Username
	 */
	new_username: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * Post
 */
export type Post = {
	/**
	 * Uuid
	 */
	uuid: string;
	/**
	 * Posted On
	 */
	posted_on: number;
	/**
	 * Content
	 */
	content: string;
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * Replies
	 */
	replies: Array<PostBase> | null;
};

/**
 * PostBase
 */
export type PostBase = {
	/**
	 * Uuid
	 */
	uuid: string;
	/**
	 * Posted On
	 */
	posted_on: number;
	/**
	 * Content
	 */
	content: string;
	/**
	 * User Id
	 */
	user_id: string;
};

/**
 * ReplyReturn
 */
export type ReplyReturn = {
	reply: PostBase;
	/**
	 * Parent Id
	 */
	parent_id: string;
};

/**
 * TokenEndpointReturn
 */
export type TokenEndpointReturn = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Token Type
	 */
	token_type: "bearer";
};

/**
 * User
 */
export type User = {
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * Creation Ts
	 */
	creation_ts: number;
	/**
	 * Username
	 */
	username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type LoginData = {
	body: BodyLogin;
	path?: never;
	query?: never;
	url: "/api/token";
};

export type LoginErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	/**
	 * Successful Response
	 */
	200: TokenEndpointReturn;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetLatestPostsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Count
		 */
		count?: number;
	};
	url: "/api/posts";
};

export type GetLatestPostsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetLatestPostsError =
	GetLatestPostsErrors[keyof GetLatestPostsErrors];

export type GetLatestPostsResponses = {
	/**
	 * Response Get Latest Posts
	 *
	 * Successful Response
	 */
	200: Array<Post>;
};

export type GetLatestPostsResponse =
	GetLatestPostsResponses[keyof GetLatestPostsResponses];

export type CreatePostData = {
	body: BodyCreatePost;
	path?: never;
	query?: never;
	url: "/api/posts";
};

export type CreatePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
	/**
	 * Successful Response
	 */
	201: Post;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetPostsByUseridData = {
	body?: never;
	path: {
		/**
		 * User Id
		 */
		user_id: string;
	};
	query?: never;
	url: "/api/users/{user_id}/posts";
};

export type GetPostsByUseridErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPostsByUseridError =
	GetPostsByUseridErrors[keyof GetPostsByUseridErrors];

export type GetPostsByUseridResponses = {
	/**
	 * Response Get Posts By Userid
	 *
	 * Successful Response
	 */
	200: Array<Post>;
};

export type GetPostsByUseridResponse =
	GetPostsByUseridResponses[keyof GetPostsByUseridResponses];

export type DeletePostData = {
	body?: never;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}";
};

export type DeletePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetPostData = {
	body?: never;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}";
};

export type GetPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
	/**
	 * Successful Response
	 */
	200: Post;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type CreateReplyData = {
	body: BodyCreateReply;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}/reply";
};

export type CreateReplyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateReplyError = CreateReplyErrors[keyof CreateReplyErrors];

export type CreateReplyResponses = {
	/**
	 * Successful Response
	 */
	201: ReplyReturn;
};

export type CreateReplyResponse =
	CreateReplyResponses[keyof CreateReplyResponses];

export type DeleteReplyData = {
	body?: never;
	path: {
		/**
		 * Reply Uuid
		 */
		reply_uuid: string;
	};
	query?: never;
	url: "/api/replies/{reply_uuid}";
};

export type DeleteReplyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteReplyError = DeleteReplyErrors[keyof DeleteReplyErrors];

export type DeleteReplyResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetUserData = {
	body?: never;
	path: {
		/**
		 * User Id
		 */
		user_id: string;
	};
	query?: never;
	url: "/api/users/{user_id}";
};

export type GetUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
	/**
	 * Successful Response
	 */
	200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetSelfData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/account/self";
};

export type GetSelfResponses = {
	/**
	 * Successful Response
	 */
	200: User;
};

export type GetSelfResponse = GetSelfResponses[keyof GetSelfResponses];

export type SetUsernameData = {
	body: BodySetUsername;
	path?: never;
	query?: never;
	url: "/api/account/changeusername";
};

export type SetUsernameErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SetUsernameError = SetUsernameErrors[keyof SetUsernameErrors];

export type SetUsernameResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type SetPasswordData = {
	body: BodySetPassword;
	path?: never;
	query?: never;
	url: "/api/account/changepassword";
};

export type SetPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SetPasswordError = SetPasswordErrors[keyof SetPasswordErrors];

export type SetPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type CreateAccountData = {
	body: BodyCreateAccount;
	path?: never;
	query?: never;
	url: "/api/account/createaccount";
};

export type CreateAccountErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
	/**
	 * Successful Response
	 */
	200: TokenEndpointReturn;
};

export type CreateAccountResponse =
	CreateAccountResponses[keyof CreateAccountResponses];

export type DeleteAccountData = {
	body: BodyDeleteAccount;
	path?: never;
	query?: never;
	url: "/api/account/deleteaccount";
};

export type DeleteAccountErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};
