// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * NewPostBody
 */
export type NewPostBody = {
	/**
	 * Content
	 */
	content: string;
	/**
	 * Username
	 */
	username: string;
};

/**
 * Post
 */
export type Post = {
	/**
	 * Uuid
	 */
	uuid: string;
	/**
	 * Posted On
	 */
	posted_on: number;
	/**
	 * Content
	 */
	content: string;
	/**
	 * Username
	 */
	username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type GetLatestPostsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Count
		 */
		count?: number;
	};
	url: "/api/posts";
};

export type GetLatestPostsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetLatestPostsError =
	GetLatestPostsErrors[keyof GetLatestPostsErrors];

export type GetLatestPostsResponses = {
	/**
	 * Response Get Latest Posts
	 *
	 * Successful Response
	 */
	200: Array<Post>;
};

export type GetLatestPostsResponse =
	GetLatestPostsResponses[keyof GetLatestPostsResponses];

export type PushPostData = {
	body: NewPostBody;
	path?: never;
	query?: never;
	url: "/api/posts";
};

export type PushPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type PushPostError = PushPostErrors[keyof PushPostErrors];

export type PushPostResponses = {
	/**
	 * Successful Response
	 */
	201: Post;
};

export type PushPostResponse = PushPostResponses[keyof PushPostResponses];

export type GetPostByUuidData = {
	body?: never;
	path: {
		/**
		 * Post Uuid
		 */
		post_uuid: string;
	};
	query?: never;
	url: "/api/posts/{post_uuid}";
};

export type GetPostByUuidErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPostByUuidError = GetPostByUuidErrors[keyof GetPostByUuidErrors];

export type GetPostByUuidResponses = {
	/**
	 * Successful Response
	 */
	200: Post;
};

export type GetPostByUuidResponse =
	GetPostByUuidResponses[keyof GetPostByUuidResponses];
